// ! Do Not Edit This File
import { Icons } from "../icons";
import { Dog } from "../types";

export const TrashButton = ({
  onClick,
  disabled = false,
}: {
  onClick: () => Promise<Dog | string>;
  disabled: boolean;
}) => (
  <img
    src={Icons.Trash}
    alt=""
    className="trash-button"
    style={{
      width: 40,
      border: 0,
      opacity: disabled ? 0.5 : 1,
      cursor: disabled ? "not-allowed" : "pointer",
    }}
    onClick={() => {
      if (!disabled) {
        void onClick();
      }
    }}
  />
);
